### ISSUE TITLE
Add links to News, Store & Settings

### ISSUE THREAD

**Issue by tariqrahiman** [eduardconstantin/Navigation-menu-animation#1]
Hello support, can you please add links to News, Store and Settings?

**Comment by tariqrahiman** [comment]
I used this  tutorial to add some links https://reactrouter.com/docs/en/v6/getting-started/concepts after 
npm install react-router-dom@6

**Comment by eduardconstantin** [comment]
> I used this tutorial to add some links https://reactrouter.com/docs/en/v6/getting-started/concepts after npm install react-router-dom@6

Yes, react router can be used to add links for each button, I will try to implement a simpler solution.

**Comment by tariqrahiman** [comment]
@eduardconstantin  That would be great, if this can be used as a starter pack for projects. Tat way you can use the same basic structure for the Comic animation project as well. Users need a generic solution to make this repo trending. But great and clean work. I am not familiar with the animation packages and looking into it

**Comment by eduardconstantin** [comment]
That makes sense! I'll have to find some time so I can take care of this project. Thank you!
