### ISSUE TITLE
Change position from center to Top Navigation

### ISSUE THREAD

**Issue by tariqrahiman** [eduardconstantin/Navigation-menu-animation#2]
Hello Support, can you please change position from center to Top Navigation

**Comment by eduardconstantin** [comment]
The menu's parent has a style that does the centering. You can position the menu anywhere you want using `position: absolute` if you remove the parent's style.

**Comment by tariqrahiman** [comment]
@eduardconstantin  I saw that styling and will play with it

**Comment by tariqrahiman** [comment]
@eduardconstantin  Can you let me know which file and line# I was not able to see anything with position:

**Comment by eduardconstantin** [comment]
you can add `position: absolute` on the parent or on the menu component.
